micronaut:
  application:
    name: kmessenger
logger:
  levels:
    com.kite.kmessanger: ERROR
cassandra:
  default:
    advanced:
      metadata:
        schema:
          enabled: false
    basic:
      contact-points:
        - "localhost:9042"
      load-balancing-policy:
        local-datacenter: datacenter1
      session-keyspace: messenger